// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shizachusmzcrqbgbpae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaXphY2h1c216Y3JxYmdicGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTk0MTUsImV4cCI6MjA2MDU3NTQxNX0.mCojCey1dOlT9hSsWQKNy1x_3W1cC9jWc5LQ12cy7Bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);